### ISSUE TITLE
Offer to Contribute and Request for Guidance and Mentorship

### ISSUE THREAD

**Issue by RocketRene** [Depado/pb-templ-htmx-tailwind#14]
Hello @Depado ,
Thank you for sharing your work with pocketbase, templ, and htmx! As someone eager to learn web development, your code is extremely helpful. I'm starting my first programming job next Monday and would love to contribute to your project in my spare time. While I'm new to contributing in open source projects and still developing my skills, I'm ready to assist wherever I can, perhaps by working on CRUD examples or improving the documentation. I'm also interested in OAuth as I develop those skills.

Could you provide some guidance on where to start? Also, do you have the capacity to offer some mentorship as I navigate my contributions?

**Comment by Depado** [comment]
Hello @RocketRene :wave: 

I'm currently working actively on this project and don't really know how it could fit in my vision to have other people working on it. I don't really know where I'm going with this project, I'm mostly just having fun and exploring different ways of working with HTMX and PocketBase (and more generally Go). 

The OAuth section will undeniably be tricky. 
My advice if you want to play around would be to fork this project and play around with it. I'll get in touch with you on Twitter so we can speak more freely than on an open issue :smile:
