### ISSUE TITLE
fly deploy

### ISSUE THREAD

**Issue by gedw99** [depado/pb-templ-htmx-tailwind#48]
Hey @depado 

The components are coming along well.

I would like to add fly deployment file.

I noticed your using GitHub CI to build a Docker also ? I mention this because Fly can use a Docker image off docker hub.  

SO we have 2 options for how to do it.

Let me know which you prefer, and I can update the makefile, etc 

---

Also Cloudflare is very often sued Wirth fly.io, so can also update make file for that if you want.

This will make it easy for devs to contribute and for CI to automatically update the site.

**Comment by depado** [comment]
Hi, I don't feel comfortable recommending something I personally don't use. I'll have a look at fly and if I feel it's suitable for this project, I'll update it accordingly.
