### ISSUE TITLE
add fly.io deployment and link to demo in README

### ISSUE THREAD

**Issue by gedw99** [Depado/pb-templ-htmx-tailwind#6]
I tend to use fly.io for demo so devs can see what it looks ike and play with it. 

fly.io is free

**Comment by gedw99** [comment]
you can also add it to the new GitHub workflow action to deploy to fly.io

They have their own registry too if you want to use it.

https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

**Comment by Depado** [comment]
Hi,
Thanks for the idea, but right now I'm not handling the deployment part of this project, and I'm not sure I want to add a demo website for it right now. I'll get back to this later :slightly_smiling_face:

**Comment by gedw99** [comment]
No worries. I will close this
